# Generated by Django 4.2.2 on 2023-06-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='РљР°С‚РµРіРѕСЂРёСЏ')),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id_division', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='РћС‚РґРµР»')),
            ],
            options={
                'db_table': 'division',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id_operation', models.TextField(primary_key=True, serialize=False)),
                ('type_operation', models.CharField(max_length=10, verbose_name='РћРїРµСЂР°С†РёСЏ')),
            ],
            options={
                'db_table': 'operation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='РЅР°Р·РІР°РЅРёРµ РїСЂРѕРґСѓРєС‚Р°')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id_main', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='Р”Р°С‚Р°')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting_of_goods.category')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting_of_goods.division')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting_of_goods.operation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting_of_goods.product')),
            ],
            options={
                'db_table': 'main',
                'managed': True,
            },
        ),
    ]
