# Generated by Django 4.2.2 on 2023-06-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_of_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Category_name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Division_name'),
        ),
        migrations.AlterField(
            model_name='main',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(max_length=10, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Product_name'),
        ),
    ]
