# Generated by Django 4.2.2 on 2023-06-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_of_goods', '0002_alter_category_name_alter_division_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='MainTable',
        ),
    ]
